### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by robertLiuLinFeng** [PKU-DAIR/Hetu-Galvatron#1]
"Could you please tell me how to use this library? I don't see the `construct_parallel_models()` API."

**Comment by Fizzmy** [comment]
You can relate to [Galvatron Model Usage](https://github.com/PKU-DAIR/Hetu-Galvatron/blob/main/galvatron/models/README.md#training-with-galvatron) for more details. The `construct_parallel_models()` API is named `construct_hybrid_parallel_model_api` in each model. It can be found in `galvatron/models/MODEL_TYPE/MODEL_TYPE_hybrid_parallel.py`.
