### ISSUE TITLE
 question about the config file

### ISSUE THREAD

**Issue by hailuoS** [PKU-DAIR/Hetu-Galvatron#2]
I saw the galvatron_config_xxx.json of the example models, the pp_degs and tp_sizes_enc are all "1", are these config files searched optimal parallelism strategy?

**Comment by Fizzmy** [comment]
Yes, these files contain the optimal parallelism strategies found on an A100 cluster. It's recommended to search for a new parallelism strategy in your own environment, as network and GPU conditions are often different.
